# Generated by Django 2.2 on 2019-04-29 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20190429_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotpic',
            name='index',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
