# Generated by Django 2.2 on 2019-04-17 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClaInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TeaInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=20)),
                ('tage', models.IntegerField()),
                ('tgender', models.BooleanField()),
                ('tcla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schooltest.ClaInfo')),
                ('tsub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schooltest.SubjectInfo')),
            ],
        ),
        migrations.CreateModel(
            name='StuInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=20)),
                ('sage', models.IntegerField()),
                ('sgender', models.BooleanField()),
                ('scla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schooltest.ClaInfo')),
            ],
        ),
    ]
